---

- name: Create IAM groups
  local_action:
    module: iam_group
    name: "{{ item.name }}"
    managed_policy: "{{ item.policy | default(omit) }}"
    users: "{{ item.users | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ iam_groups }}"

